'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/font.scss";
import "@/styles/reset.scss";
import "@/styles/var.scss";
import "@/styles/globals.scss";
import Header from "@/widgets/header/Header";
import Footer from "@/widgets/footer/Footer"

// import { $errorPage } from '@/store/ErrorPage/ErrorPage'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const errorStore = useUnit($errorPage)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>




    </html>
  );
}
